AWSTemplateFormatVersion: '2010-09-09'
Description: Cross-Account Role for AMI Usage Checker (Deploy in target accounts)

Parameters:
  TrustedAccountId:
    Type: String
    Description: AWS Account ID where the Lambda function is deployed
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be a 12-digit AWS account ID

  RoleName:
    Type: String
    Default: AMICheckerRole
    Description: Name of the role to create

Resources:
  AMICheckerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: Allows AMI usage checking from trusted account
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${TrustedAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: ami-checker
      ManagedPolicyArns:
        - !Ref AMICheckerPolicy
      Tags:
        - Key: Purpose
          Value: AMI-Usage-Checker

  AMICheckerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: AMICheckerPolicy
      Description: Permissions for AMI usage checking
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AMIUsageReports
            Effect: Allow
            Action:
              - ec2:CreateImageUsageReport
              - ec2:DescribeImageUsageReports
              - ec2:DescribeImageUsageReportEntries
              - ec2:DeleteImageUsageReport
            Resource: '*'
          
          - Sid: AMIReferenceCheck
            Effect: Allow
            Action:
              - ec2:DescribeImageReferences
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeLaunchTemplates
              - ec2:DescribeLaunchTemplateVersions
            Resource: '*'
          
          - Sid: SSMParameters
            Effect: Allow
            Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
            Resource: '*'
          
          - Sid: ImageBuilder
            Effect: Allow
            Action:
              - imagebuilder:ListImageRecipes
              - imagebuilder:ListContainerRecipes
              - imagebuilder:GetContainerRecipe
            Resource: '*'

Outputs:
  RoleArn:
    Description: ARN of the created role
    Value: !GetAtt AMICheckerRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  RoleName:
    Description: Name of the created role
    Value: !Ref RoleName
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
