AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS AMI Usage Checker Lambda Function

Parameters:
  AssumeRoleName:
    Type: String
    Default: AMICheckerRole
    Description: Role name to assume in target accounts (optional)

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.12

Resources:
  AMICheckerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: AMICheckerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeImages
                  - ec2:CreateImageUsageReport
                  - ec2:DescribeImageUsageReports
                  - ec2:DescribeImageUsageReportEntries
                  - ec2:DescribeImageReferences
                Resource: '*'
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - !Sub 'arn:${AWS::Partition}:iam::*:role/${AssumeRoleName}'

  AMICheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AMIUsageChecker
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Description: Check AMI usage across accounts
      Role: !GetAtt AMICheckerFunctionRole.Arn
      Environment:
        Variables:
          ASSUME_ROLE_NAME: !Ref AssumeRoleName
      Events:
        ScheduledCheck:
          Type: Schedule
          Properties:
            Schedule: cron(0 2 ? * MON *)  # Every Monday at 2 AM UTC
            Description: Weekly AMI usage check
            Enabled: false  # Disabled by default

  AMICheckerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AMICheckerFunction}'
      RetentionInDays: 7

Outputs:
  FunctionArn:
    Description: AMI Checker Lambda Function ARN
    Value: !GetAtt AMICheckerFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'
  
  FunctionName:
    Description: AMI Checker Lambda Function Name
    Value: !Ref AMICheckerFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'
